---
- name: Provision vagrant
  hosts: all
  tasks:
  - name: Set LS_COLORS in .bashrc for Visual Studio Code / Git Bash Display
    become: false
    lineinfile:
      path: $HOME/.bashrc
      regexp: '^LS_COLORS='
      line: export LS_COLORS="ow=01;36;40"
